version: '3.7'

services:
  # App (Vue)
  app:
    build:
      context: ./dockerfiles
      dockerfile: vue.dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.localhost`) && PathPrefix(`/`)"
      - "traefik.http.services.app.loadbalancer.server.port=8081"
    depends_on:
      - api
      - traefik

  # API
  api:
    build:
      context: ./dockerfiles
      dockerfile: laravel.dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./backend:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=(Host(`app.localhost`) && PathPrefix(`/api`))"
      - "traefik.http.services.api.loadbalancer.server.port=8082"
    depends_on:
      - mysql
      - traefik

  # MySQL
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: data_filter_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root_mysql
      MYSQL_ROOT_PASSWORD: root_mysql
    volumes:
      - ../db-data-filter:/var/lib/mysql

  # Traefik
  traefik:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock